import type { Metadata } from "next";
import "@/styles/globals.css";
import Nav from "@/components/nav/Nav";
import { ArticlesProvider } from "@/context/articleContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <ArticlesProvider>
          <Nav />
          <main className="max-w-6xl mx-auto min-h-full pt-20">
            {children}
          </main>
        </ArticlesProvider>
      </body>
    </html>
  );
}
